### ISSUE TITLE
TODO-list

### ISSUE THREAD

**Issue by linkdata** [linkdata/rap#2]
- [x] Remove `fasthttp`. Not needed since we can scale by adding more gateways
- [x] Examine feasibility of writing protocol handler in C for use with all languages: [crap](https://github.com/linkdata/crap)
- [x] Write unit tests
- [x] Start using `pkg/errors` so we get stack traces from where it was
- [ ] Add support for [`context`](https://golang.org/pkg/context/)
- [ ] Add support for HTTP [Trailers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Trailer)
- [ ] Write benchmarks
- [ ] Code cleanup
- [x] Add websockets support
- [ ] Add routing
- [ ] Add per-side dynamic dictionary to protocol
- [ ] Improve documentation on interfaces and methods
- [ ] Make a graphical overview of protocol
- [ ] Possibly refactor into subprojects
